### ISSUE TITLE
Add Signup/Registration Feature for New Users

### ISSUE THREAD

**Issue by Amulya-Codes** [minikopi/siads#12]
## Description:

-The current system includes a login feature but does not offer a signup or registration option for new users. To improve user experience, adding a signup/registration functionality would allow new users to create their accounts directly. This feature would make the system more accessible and enhance user engagement by streamlining the process for new users to join the platform.
![IMG_3056](https://github.com/user-attachments/assets/e2394371-62a1-4ff9-bb9d-44815a4c72b8)

**Comment by AaEzha** [comment]
@Amulya-Codes thank you for your concern.

We do add/register new user inside the panel by administrator, not from outside form. Why? Because this is some internal system to use for.
